[project]
name = "goa-bulk-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "drawsvg>=2.4.0",
    "osmnx>=2.0.7",
    "pydantic>=2.12.5",
    "tqdm>=4.67.1",
]
